# Generated by Django 2.2.12 on 2020-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200805_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
    ]
