# Generated by Django 2.2.12 on 2020-06-20 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creacion registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion'),
        ),
    ]
