# Generated by Django 2.2.12 on 2020-07-15 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animal', '0002_auto_20200620_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltratamiento',
            name='fecha_tratamiento',
            field=models.DateField(verbose_name='Fecha de aplicacion'),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, max_length=400)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_imagen', models.ImageField(blank=True, null=True, upload_to='publicacion')),
                ('Publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Publicacion')),
            ],
        ),
    ]
