# Generated by Django 2.2.12 on 2020-07-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_auto_20200715_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenpublicacion',
            old_name='Publicacion',
            new_name='publicacion',
        ),
    ]
