# Generated by Django 2.2.12 on 2020-07-15 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animal', '0005_auto_20200715_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosSolicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Solicitud')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal')),
                ('estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.EstadosSolicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
