# Generated by Django 2.2.12 on 2020-07-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_estadossolicitud_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadossolicitud',
            options={'verbose_name': 'Estado solicitud', 'verbose_name_plural': 'Estados de solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud Animal', 'verbose_name_plural': 'Solicitudes Animales'},
        ),
        migrations.AlterModelTable(
            name='estadossolicitud',
            table='ESTADO_SOLICITUD',
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table='SOLICITUD',
        ),
    ]
